### ISSUE TITLE
Support global style rules

### ISSUE THREAD

**Issue by steadicat** [martinandert/babel-plugin-css-in-js#16]
It would be great if it were an escape hatch that would allow you to specify global style rules in JS as well, without having to use a separate syntax and pipeline for it.

There could be a special syntax that would opt a rule out of the selector rewriting. For example:

```JS
const globalStyles = cssInJS({
  '$body': {margin: 0},
  '$.small-caps': {textTransform: 'uppercase', fontSize: '0.9%'},
});
```

This would inject the following into the generated stylesheet:
```css
body {margin: 0px}
.small-caps {text-transform: uppercase; font-size: 0.9%}
```
