### ISSUE TITLE
About more universal Nested Rules

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [martinandert/babel-plugin-css-in-js#26]
Currently `babel-plugin-css-in-js` support some nested rules using global selectors `$`, but they are very limited. I'm considering implementing nested rules for a universal case used in css pre-processes such as less and stylus. ( see the example below )

Component:
```jsx
<div className={ st.box }>
  <div className={ st.hiddenBtn }/>
</div>
```

css-in-js
```js
const st = cssInJS({
  box: {
    color: 'red',
  },

  hiddenBtn: {
    opacity: 0
  },

  // I want to follow Nested Rules
  'box:hover': {
    '.hiddenBtn': {
      opacity: 1,
    }
  }
})
```

babel:
```js
const st = {
  box: 'dir_filename_js-styles-box',
  hiddenBtn: 'dir_filename_js-styles-hiddenBtn'
}
```

css
```css
.dir_filename_js-styles-box {
  color: red;
}
.dir_filename_js-styles-hiddenBtn {
  opacity: 0;
}
.dir_filename_js-styles-box:hover .dir_filename_js-styles-hiddenBtn {
  opacity: 1;
}
```

![screen shot 2017-03-27 at 8 22 18 pm](https://cloud.githubusercontent.com/assets/15520015/24353974/1f6dcba8-132b-11e7-8991-6a8e88bbca4e.png)
[Image1]

In the First `box` in `Image1` `.box .hiddenBtn` selector works well. But in the second box, `.box .hiddenBtn` selector will select all `.hiddenBtn` in the box.
it might be a bug. (Because developers always can write `.box .hiddenBtn` selector instead of `.box > .hiddenBtn` selector,  I don't mention about `.box > .hiddenBtn` selector here )

So I like the globally unique (randomized) className this plugin creates. Ever since I use this plugin, no matter how big the application was, there was no bug affected by the unintentional css rule. In order to keep this benefit, in  nested rules, both `box` and `hiddenBtn` must be uniqued.

The global selector concept is great for theme, but I want to implement nested rules with a more universal concept that is used by other pre-processors that operate independently of the global selector nested rules.

Could I make some PR?

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I also want to use `&`.
(`&` represents the current selector parent)

css-in-js:
```js
const st = cssInJS({
  box: {
    color: 'red',
    width: 100,
    height: 40,
    '&:hover': {
      color: 'blue',
      '.hiddenBtn': {
        opacity: 1
      },
      '& > .normalBtn': {
        marginRight: 10
      }
    }
  }
})
```

css:
```css
.dir_filename_js-styles-box {
  color: red;
  width: 100px;
  height: 40px;
}
.dir_filename_js-styles-box:hover {
  color: blue;
}
.dir_filename_js-styles-box:hover .dir_filename_js-styles-hiddenBtn {
  opacity: 1;
}
.dir_filename_js-styles-box:hover > .dir_filename_js-styles-normalBtn {
  marginRight: 10px;
}
```
